#!/bin/sh

set -e

# Parse image name for repo name
#TAG_START=$(expr index "$IMAGE_NAME" :)
#REPO_NAME=${IMAGE_NAME:0:TAG_START-1}

# DOCKER_REPO
# DOCKER_TAG

# Tag and push image for each additional tag
for TAG in {latest}; do
    echo "${REPO_NAME}:${TAG}"
#    docker tag $IMAGE_NAME ${REPO_NAME}:${TAG}
#    docker push ${REPO_NAME}:${TAG}
done

